---
title: "Datos de cantones de Costa Rica"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```


```{r paquetes, message=FALSE, warning=FALSE}
library(dplyr)
library(sf)
library(leaflet)
library(DT)
library(ggplot2)
library(leaflet)
library(plotly)
```

```{r lectura_de_datos}
cantones <-
  st_read( dsn= "cantones_simplificados.geojson", quiet=TRUE) %>%
  st_transform(4326)
```

Column {data-width=550}
-----------------------------------------------------------------------

### mapa de cantones

```{r mapa}
leaflet() %>%
  addTiles() %>%
  addPolygons(data = cantones, weight = 1.0)

```

Column {data-width=450}
-----------------------------------------------------------------------

### tabla de cantones

```{r tabla}
cantones %>%
  st_drop_geometry() %>%
  select(provincia, canton, area) %>%
  datatable(
    colnames = c("Provincia", "Canton", "Area"),
    options = list(
    pageLength = 5,
    language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
  ))
```

### gráfico de cantones

```{r gráfico_de_cantones}
ggplot2_grafico_cantones <-
cantones %>%
  st_drop_geometry()%>%
  slice_max(area, n = 15) %>% 
  ggplot(aes(x = reorder(canton, -area), y = area)) +
  geom_bar(stat = "identity") +
  ggtitle("Área de cada cantón") +
  xlab("Cantón") +
  ylab("Área") +
  coord_flip() 

ggplotly(ggplot2_grafico_cantones) %>% config(locale = 'es')
```

